server:
  port: 1258
  servlet:
    session:
      cookie:
        same-site: none
  ssl:
    protocol: TLS
    key-store: classpath:keystore.p12
    key-store-type: JKS
    key-store-password: zwf123
#  shutdown: graceful
spring:
  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 1800
    lettuce:
      pool:
        max-active: 20
        max-wait: 1
        max-idle: 5
        min-idle: 11
springdoc:
  packages-to-scan: com.example.nicqbasespring.controller