server:
  port: 1258
  servlet:
    session:
      cookie:
        same-site: none
  ssl:
    protocol: TLS
    key-store: classpath:192.168.10.1.p12
    key-store-type: JKS
    key-store-password: changeit
#  shutdown: graceful
spring:
  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 1800
    lettuce:
      pool:
        max-active: 20
        max-wait: 1
        max-idle: 5
        min-idle: 11
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
springdoc:
  packages-to-scan: com.example.nicqbasespring.controller
logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %yellow(at %class.%method) \\(%file:%line\\) %n%clr(>>>>>>) %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"